import type { RegionAssetCategory } from "@rustcraft/shared";

/** Curated, prefix-grouped organisation of the real nature/building asset
 *  directories for the region editor's asset palette (parallels
 *  dungeonPropPalette.ts's role for the dungeon editor). `category` records
 *  which real directory under assets/models/ each group's files live under
 *  (foliage/, buildings/, props/), since the loader needs the right path
 *  prefix and a RegionAsset can't infer it from the filename alone the way
 *  the dungeon editor's props-only palette could. */
export interface RegionPropPaletteGroup {
  label: string;
  category: RegionAssetCategory;
  models: string[];
  /** Optional pack override; otherwise inferred from label / model path. */
  pack?: string;
}

export const REGION_ASSET_DIR: Record<RegionAssetCategory, string> = {
  building: "buildings",
  foliage: "foliage",
  prop: "props",
};

export interface RegionPaletteAsset {
  model: string;
  category: RegionAssetCategory;
  group: string;
  pack: string;
}

/** Top-level Asset Explorer / palette pack filters. */
export const REGION_PALETTE_PACKS: { id: string; label: string }[] = [
  { id: "all", label: "All packs" },
  { id: "Core", label: "Core" },
  { id: "Medieval Village", label: "Medieval Village" },
  { id: "Stylized Nature", label: "Stylized Nature" },
  { id: "Castle Pack", label: "Castle Pack" },
  { id: "KayKit Hexagon", label: "KayKit Hexagon" },
  { id: "Fantastic Village", label: "Fantastic Village" },
  { id: "Free Low Poly", label: "Free Low Poly" },
];

export const REGION_PALETTE_CATEGORIES: { id: RegionAssetCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "foliage", label: "Foliage" },
  { id: "building", label: "Buildings" },
  { id: "prop", label: "Props" },
];

/** Infer asset pack from group label or first model path. */
export function regionPackForGroup(label: string, models: string[] = []): string {
  if (label.startsWith("FV ·")) return "Fantastic Village";
  if (label.startsWith("FL ·")) return "Free Low Poly";
  if (label.startsWith("CP ·") || label === "Castle Ruins") return "Castle Pack";
  if (label.startsWith("KH ·")) return "KayKit Hexagon";
  if (label.startsWith("MV ·")) return "Medieval Village";
  if (label.startsWith("SN ·")) return "Stylized Nature";
  const sample = models[0] ?? "";
  if (sample.includes("fantastic_village/")) return "Fantastic Village";
  if (sample.includes("free_lowpoly/")) return "Free Low Poly";
  if (sample.includes("castle_pack/") || sample.includes("castle_ruins/")) return "Castle Pack";
  if (sample.includes("kaykit_hexagon/")) return "KayKit Hexagon";
  if (sample.includes("medieval_village/")) return "Medieval Village";
  if (sample.includes("stylized_nature/")) return "Stylized Nature";
  return "Core";
}

export function regionGroupPack(group: RegionPropPaletteGroup): string {
  return group.pack ?? regionPackForGroup(group.label, group.models);
}
export const REGION_PROP_PALETTE: RegionPropPaletteGroup[] = [
  {
    label: "Trees",
    category: "foliage",
    models: [
      "oak_1.glb", "oak_2.glb", "oak_3.glb", "oak_4.glb", "oak_5.glb",
      "pine_1.glb", "pine_2.glb", "pine_3.glb", "pine_4.glb", "pine_5.glb",
      "twisted_1.glb", "twisted_2.glb", "twisted_3.glb",
      "dead_1.glb", "dead_2.glb", "dead_3.glb",
    ],
  },
  {
    label: "Ground Cover",
    category: "foliage",
    models: ["bush.glb", "bush_flowers.glb", "fern.glb", "mushroom.glb"],
  },
  {
    label: "Small Rocks",
    category: "foliage",
    models: ["rock_1.glb", "rock_2.glb", "rock_3.glb"],
  },
  {
    label: "Rocks & Boulders",
    category: "prop",
    models: ["rocks.gltf", "rocks_decorated.gltf", "rocks_gold.gltf", "rocks_small.gltf"],
  },
  {
    label: "Lighting Props",
    category: "prop",
    models: ["post_lantern.glb"],
  },
  {
    label: "Buildings",
    category: "building",
    models: [
      "building_home_A.gltf", "building_home_B.gltf", "building_tavern.gltf",
      "building_blacksmith.gltf", "building_market.gltf", "building_church.gltf",
      "building_windmill.gltf", "building_lumbermill.gltf", "building_well.gltf",
      "building_tower_A.gltf", "building_destroyed.gltf", "building_grain.gltf",
      "building_bridge_A.gltf", "building_bridge_B.gltf",
    ],
  },
  {
    label: "Village Clutter",
    category: "building",
    models: [
      "barrel.gltf", "bucket_water.gltf", "crate_A_big.gltf", "crate_A_small.gltf",
      "crate_B_small.gltf", "fence_stone_straight.gltf", "fence_wood_straight.gltf",
      "fence_wood_straight_gate.gltf", "flag_blue.gltf", "flag_red.gltf",
    ],
  },

  // ── Medieval Village MegaKit [Standard] ──────────────────────────────────
  // Files live in public/assets/models/buildings/medieval_village/
  // Model strings include the subfolder prefix; the loader concatenates them
  // as: /assets/models/buildings/{model}
  {
    label: "MV · Walls (Plaster)",
    category: "building",
    models: [
      "medieval_village/Wall_Plaster_Straight.gltf",
      "medieval_village/Wall_Plaster_Straight_Base.gltf",
      "medieval_village/Wall_Plaster_Straight_L.gltf",
      "medieval_village/Wall_Plaster_Straight_R.gltf",
      "medieval_village/Wall_Plaster_Door_Flat.gltf",
      "medieval_village/Wall_Plaster_Door_Round.gltf",
      "medieval_village/Wall_Plaster_Door_RoundInset.gltf",
      "medieval_village/Wall_Plaster_Window_Thin_Round.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Flat.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Flat2.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Round.gltf",
      "medieval_village/Wall_Plaster_WoodGrid.gltf",
      "medieval_village/Wall_Arch.gltf",
      "medieval_village/Wall_BottomCover.gltf",
    ],
  },
  {
    label: "MV · Walls (Brick)",
    category: "building",
    models: [
      "medieval_village/Wall_UnevenBrick_Straight.gltf",
      "medieval_village/Wall_UnevenBrick_Door_Flat.gltf",
      "medieval_village/Wall_UnevenBrick_Door_Round.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Thin_Round.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Wide_Flat.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Wide_Round.gltf",
    ],
  },
  {
    label: "MV · Corners",
    category: "building",
    models: [
      "medieval_village/Corner_Exterior_Brick.gltf",
      "medieval_village/Corner_ExteriorWide_Brick.gltf",
      "medieval_village/Corner_Exterior_Wood.gltf",
      "medieval_village/Corner_ExteriorWide_Wood.gltf",
      "medieval_village/Corner_Exterior_TopDown.gltf",
      "medieval_village/Corner_Exterior_TopOnly.gltf",
      "medieval_village/Corner_Interior_Big.gltf",
      "medieval_village/Corner_Interior_Small.gltf",
    ],
  },
  {
    label: "MV · Doors & Windows",
    category: "building",
    models: [
      "medieval_village/Door_1_Flat.gltf",
      "medieval_village/Door_1_Round.gltf",
      "medieval_village/Door_2_Flat.gltf",
      "medieval_village/Door_2_Round.gltf",
      "medieval_village/Door_4_Flat.gltf",
      "medieval_village/Door_4_Round.gltf",
      "medieval_village/Door_8_Flat.gltf",
      "medieval_village/Door_8_Round.gltf",
      "medieval_village/DoorFrame_Flat_Brick.gltf",
      "medieval_village/DoorFrame_Flat_WoodDark.gltf",
      "medieval_village/DoorFrame_Round_Brick.gltf",
      "medieval_village/DoorFrame_Round_WoodDark.gltf",
      "medieval_village/Window_Thin_Flat1.gltf",
      "medieval_village/Window_Thin_Round1.gltf",
      "medieval_village/Window_Wide_Flat1.gltf",
      "medieval_village/Window_Wide_Round1.gltf",
      "medieval_village/Window_Roof_Thin.gltf",
      "medieval_village/Window_Roof_Wide.gltf",
      "medieval_village/WindowShutters_Thin_Flat_Closed.gltf",
      "medieval_village/WindowShutters_Thin_Flat_Open.gltf",
      "medieval_village/WindowShutters_Thin_Round_Closed.gltf",
      "medieval_village/WindowShutters_Thin_Round_Open.gltf",
      "medieval_village/WindowShutters_Wide_Flat_Closed.gltf",
      "medieval_village/WindowShutters_Wide_Flat_Open.gltf",
      "medieval_village/WindowShutters_Wide_Round_Closed.gltf",
      "medieval_village/WindowShutters_Wide_Round_Open.gltf",
    ],
  },
  {
    label: "MV · Floors",
    category: "building",
    models: [
      "medieval_village/Floor_Brick.gltf",
      "medieval_village/Floor_RedBrick.gltf",
      "medieval_village/Floor_UnevenBrick.gltf",
      "medieval_village/Floor_WoodDark.gltf",
      "medieval_village/Floor_WoodDark_Half1.gltf",
      "medieval_village/Floor_WoodDark_Half2.gltf",
      "medieval_village/Floor_WoodDark_Half3.gltf",
      "medieval_village/Floor_WoodDark_OverhangCorner.gltf",
      "medieval_village/Floor_WoodDark_OverhangCorner2.gltf",
      "medieval_village/Floor_WoodLight.gltf",
      "medieval_village/Floor_WoodLight_OverhangCorner.gltf",
      "medieval_village/Floor_WoodLight_OverhangCorner2.gltf",
      "medieval_village/HoleCover_90Angle.gltf",
      "medieval_village/HoleCover_90Half.gltf",
      "medieval_village/HoleCover_90Stairs.gltf",
      "medieval_village/HoleCover_Straight.gltf",
      "medieval_village/HoleCover_StraightHalf.gltf",
    ],
  },
  {
    label: "MV · Roofs (Round Tiles)",
    category: "building",
    models: [
      "medieval_village/Roof_RoundTile_2x1.gltf",
      "medieval_village/Roof_RoundTile_2x1_Long.gltf",
      "medieval_village/Roof_2x4_RoundTile.gltf",
      "medieval_village/Roof_RoundTiles_4x4.gltf",
      "medieval_village/Roof_RoundTiles_4x6.gltf",
      "medieval_village/Roof_RoundTiles_4x8.gltf",
      "medieval_village/Roof_RoundTiles_6x4.gltf",
      "medieval_village/Roof_RoundTiles_6x6.gltf",
      "medieval_village/Roof_RoundTiles_6x8.gltf",
      "medieval_village/Roof_RoundTiles_6x10.gltf",
      "medieval_village/Roof_RoundTiles_6x12.gltf",
      "medieval_village/Roof_RoundTiles_6x14.gltf",
      "medieval_village/Roof_RoundTiles_8x8.gltf",
      "medieval_village/Roof_RoundTiles_8x10.gltf",
      "medieval_village/Roof_RoundTiles_8x12.gltf",
      "medieval_village/Roof_RoundTiles_8x14.gltf",
      "medieval_village/Roof_Modular_RoundTiles.gltf",
      "medieval_village/Roof_Tower_RoundTiles.gltf",
      "medieval_village/Roof_Dormer_RoundTile.gltf",
    ],
  },
  {
    label: "MV · Roofs (Wooden)",
    category: "building",
    models: [
      "medieval_village/Roof_Wooden_2x1.gltf",
      "medieval_village/Roof_Wooden_2x1_L.gltf",
      "medieval_village/Roof_Wooden_2x1_R.gltf",
      "medieval_village/Roof_Wooden_2x1_Center.gltf",
      "medieval_village/Roof_Wooden_2x1_Center_Mirror.gltf",
      "medieval_village/Roof_Wooden_2x1_Corner.gltf",
      "medieval_village/Roof_Wooden_2x1_Middle.gltf",
    ],
  },
  {
    label: "MV · Roof Fronts & Overhangs",
    category: "building",
    models: [
      "medieval_village/Roof_Front_Brick2.gltf",
      "medieval_village/Roof_Front_Brick4.gltf",
      "medieval_village/Roof_Front_Brick4_Half_L.gltf",
      "medieval_village/Roof_Front_Brick4_Half_R.gltf",
      "medieval_village/Roof_Front_Brick6.gltf",
      "medieval_village/Roof_Front_Brick6_Half_L.gltf",
      "medieval_village/Roof_Front_Brick6_Half_R.gltf",
      "medieval_village/Roof_Front_Brick8.gltf",
      "medieval_village/Roof_Front_Brick8_Half_L.gltf",
      "medieval_village/Roof_Front_Brick8_Half_R.gltf",
      "medieval_village/Roof_FrontSupports.gltf",
      "medieval_village/Roof_Log.gltf",
      "medieval_village/Roof_Support2.gltf",
      "medieval_village/Overhang_Plaster_Corner.gltf",
      "medieval_village/Overhang_Plaster_Corner_Front.gltf",
      "medieval_village/Overhang_Plaster_Long.gltf",
      "medieval_village/Overhang_Plaster_Short.gltf",
      "medieval_village/Overhang_Roof_Plaster.gltf",
      "medieval_village/Overhang_RoofIncline_Plaster.gltf",
      "medieval_village/Overhang_UnevenBrick_Corner.gltf",
      "medieval_village/Overhang_UnevenBrick_Corner_Front.gltf",
      "medieval_village/Overhang_UnevenBrick_Long.gltf",
      "medieval_village/Overhang_UnevenBrick_Short.gltf",
      "medieval_village/Overhang_Roof_UnevenBricks.gltf",
      "medieval_village/Overhang_RoofIncline_UnevenBricks.gltf",
      "medieval_village/Overhang_Side_Plaster_Long_L.gltf",
      "medieval_village/Overhang_Side_Plaster_Long_R.gltf",
      "medieval_village/Overhang_Side_Plaster_Short_L.gltf",
      "medieval_village/Overhang_Side_Plaster_Short_R.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Long_L.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Long_R.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Short_L.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Short_R.gltf",
    ],
  },
  {
    label: "MV · Stairs (Exterior)",
    category: "building",
    models: [
      "medieval_village/Stairs_Exterior_Straight.gltf",
      "medieval_village/Stairs_Exterior_Straight_L.gltf",
      "medieval_village/Stairs_Exterior_Straight_R.gltf",
      "medieval_village/Stairs_Exterior_Straight_Center.gltf",
      "medieval_village/Stairs_Exterior_Platform.gltf",
      "medieval_village/Stairs_Exterior_Platform45.gltf",
      "medieval_village/Stairs_Exterior_Platform45Clean.gltf",
      "medieval_village/Stairs_Exterior_PlatformU.gltf",
      "medieval_village/Stairs_Exterior_SidePlatform.gltf",
      "medieval_village/Stairs_Exterior_Sides.gltf",
      "medieval_village/Stairs_Exterior_Sides45.gltf",
      "medieval_village/Stairs_Exterior_SidesU.gltf",
      "medieval_village/Stairs_Exterior_SingleSide.gltf",
      "medieval_village/Stairs_Exterior_SingleSideThick.gltf",
      "medieval_village/Stairs_Exterior_NoFirstStep.gltf",
    ],
  },
  {
    label: "MV · Stairs (Interior)",
    category: "building",
    models: [
      "medieval_village/Stair_Interior_Simple.gltf",
      "medieval_village/Stair_Interior_Solid.gltf",
      "medieval_village/Stair_Interior_SolidExtended.gltf",
      "medieval_village/Stair_Interior_Rails.gltf",
    ],
  },
  {
    label: "MV · Balconies",
    category: "building",
    models: [
      "medieval_village/Balcony_Simple_Straight.gltf",
      "medieval_village/Balcony_Simple_Corner.gltf",
      "medieval_village/Balcony_Cross_Straight.gltf",
      "medieval_village/Balcony_Cross_Corner.gltf",
    ],
  },
  {
    label: "MV · Props & Fences",
    category: "building",
    models: [
      "medieval_village/Prop_Crate.gltf",
      "medieval_village/Prop_Wagon.gltf",
      "medieval_village/Prop_Chimney.gltf",
      "medieval_village/Prop_Chimney2.gltf",
      "medieval_village/Prop_Support.gltf",
      "medieval_village/Prop_WoodenFence_Single.gltf",
      "medieval_village/Prop_WoodenFence_Extension1.gltf",
      "medieval_village/Prop_WoodenFence_Extension2.gltf",
      "medieval_village/Prop_MetalFence_Simple.gltf",
      "medieval_village/Prop_MetalFence_Ornament.gltf",
      "medieval_village/Prop_ExteriorBorder_Corner.gltf",
      "medieval_village/Prop_ExteriorBorder_Straight1.gltf",
      "medieval_village/Prop_ExteriorBorder_Straight2.gltf",
      "medieval_village/Prop_Brick1.gltf",
      "medieval_village/Prop_Brick2.gltf",
      "medieval_village/Prop_Brick3.gltf",
      "medieval_village/Prop_Brick4.gltf",
      "medieval_village/Prop_Vine1.gltf",
      "medieval_village/Prop_Vine2.gltf",
      "medieval_village/Prop_Vine4.gltf",
      "medieval_village/Prop_Vine5.gltf",
      "medieval_village/Prop_Vine6.gltf",
      "medieval_village/Prop_Vine9.gltf",
    ],
  },

  // ── Stylized Nature MegaKit [Standard] ───────────────────────────────────
  // Files live in public/assets/models/foliage/stylized_nature/
  // Model strings include the subfolder prefix; the loader concatenates them
  // as: /assets/models/foliage/{model}
  {
    label: "SN · Common Trees",
    category: "foliage",
    models: [
      "stylized_nature/CommonTree_1.gltf",
      "stylized_nature/CommonTree_2.gltf",
      "stylized_nature/CommonTree_3.gltf",
      "stylized_nature/CommonTree_4.gltf",
      "stylized_nature/CommonTree_5.gltf",
    ],
  },
  {
    label: "SN · Pine Trees",
    category: "foliage",
    models: [
      "stylized_nature/Pine_1.gltf",
      "stylized_nature/Pine_2.gltf",
      "stylized_nature/Pine_3.gltf",
      "stylized_nature/Pine_4.gltf",
      "stylized_nature/Pine_5.gltf",
    ],
  },
  {
    label: "SN · Dead & Twisted Trees",
    category: "foliage",
    models: [
      "stylized_nature/DeadTree_1.gltf",
      "stylized_nature/DeadTree_2.gltf",
      "stylized_nature/DeadTree_3.gltf",
      "stylized_nature/DeadTree_4.gltf",
      "stylized_nature/DeadTree_5.gltf",
      "stylized_nature/TwistedTree_1.gltf",
      "stylized_nature/TwistedTree_2.gltf",
      "stylized_nature/TwistedTree_3.gltf",
      "stylized_nature/TwistedTree_4.gltf",
      "stylized_nature/TwistedTree_5.gltf",
    ],
  },
  {
    label: "SN · Bushes & Ground Cover",
    category: "foliage",
    models: [
      "stylized_nature/Bush_Common.gltf",
      "stylized_nature/Bush_Common_Flowers.gltf",
      "stylized_nature/Fern_1.gltf",
      "stylized_nature/Mushroom_Common.gltf",
      "stylized_nature/Mushroom_Laetiporus.gltf",
      "stylized_nature/Plant_1.gltf",
      "stylized_nature/Plant_1_Big.gltf",
      "stylized_nature/Plant_7.gltf",
      "stylized_nature/Plant_7_Big.gltf",
      "stylized_nature/Clover_1.gltf",
      "stylized_nature/Clover_2.gltf",
    ],
  },
  {
    label: "SN · Flowers & Grass",
    category: "foliage",
    models: [
      "stylized_nature/Flower_3_Single.gltf",
      "stylized_nature/Flower_3_Group.gltf",
      "stylized_nature/Flower_4_Single.gltf",
      "stylized_nature/Flower_4_Group.gltf",
      "stylized_nature/Grass_Common_Short.gltf",
      "stylized_nature/Grass_Common_Tall.gltf",
      "stylized_nature/Grass_Wispy_Short.gltf",
      "stylized_nature/Grass_Wispy_Tall.gltf",
    ],
  },
  {
    label: "SN · Rocks & Pebbles",
    category: "foliage",
    models: [
      "stylized_nature/Rock_Medium_1.gltf",
      "stylized_nature/Rock_Medium_2.gltf",
      "stylized_nature/Rock_Medium_3.gltf",
      "stylized_nature/Pebble_Round_1.gltf",
      "stylized_nature/Pebble_Round_2.gltf",
      "stylized_nature/Pebble_Round_3.gltf",
      "stylized_nature/Pebble_Round_4.gltf",
      "stylized_nature/Pebble_Round_5.gltf",
      "stylized_nature/Pebble_Square_1.gltf",
      "stylized_nature/Pebble_Square_2.gltf",
      "stylized_nature/Pebble_Square_3.gltf",
      "stylized_nature/Pebble_Square_4.gltf",
      "stylized_nature/Pebble_Square_5.gltf",
      "stylized_nature/Pebble_Square_6.gltf",
    ],
  },
  {
    label: "SN · Rock Paths",
    category: "foliage",
    models: [
      "stylized_nature/RockPath_Round_Small_1.gltf",
      "stylized_nature/RockPath_Round_Small_2.gltf",
      "stylized_nature/RockPath_Round_Small_3.gltf",
      "stylized_nature/RockPath_Round_Thin.gltf",
      "stylized_nature/RockPath_Round_Wide.gltf",
      "stylized_nature/RockPath_Square_Small_1.gltf",
      "stylized_nature/RockPath_Square_Small_2.gltf",
      "stylized_nature/RockPath_Square_Small_3.gltf",
      "stylized_nature/RockPath_Square_Thin.gltf",
      "stylized_nature/RockPath_Square_Wide.gltf",
    ],
  },

  // ── 3d Castle Pack (full Meshes/ export) ─────────────────────────────────
  // Files live in public/assets/models/buildings/castle_pack/
  {
    label: "CP · Round Towers",
    category: "building",
    models: [
      "castle_pack/tower_round.gltf",
      "castle_pack/tower_round_interior.gltf",
      "castle_pack/tower_round_bottom.gltf",
      "castle_pack/tower_small.gltf",
    ],
  },
  {
    label: "CP · Square Towers",
    category: "building",
    models: [
      "castle_pack/tower_square.gltf",
      "castle_pack/tower_square_interior.gltf",
      "castle_pack/tower_square_bottom.gltf",
      "castle_pack/tower_square_top.gltf",
    ],
  },
  {
    label: "CP · Tower Roofs",
    category: "building",
    models: [
      "castle_pack/roof_cone.gltf",
      "castle_pack/roof_round_extension.gltf",
      "castle_pack/roof_round_stone.gltf",
      "castle_pack/roof_round_stone_rock.gltf",
      "castle_pack/roof_square.gltf",
      "castle_pack/roof_square_edge.gltf",
      "castle_pack/roof_square_hollow.gltf",
      "castle_pack/roof_square_block.gltf",
      "castle_pack/roof_square_wood.gltf",
      "castle_pack/roof_corner_cone.gltf",
    ],
  },
  {
    label: "CP · Curtain Walls & Gates",
    category: "building",
    models: [
      "castle_pack/wall_large.gltf",
      "castle_pack/wall_chunk.gltf",
      "castle_pack/wall_shoot.gltf",
      "castle_pack/wall_slit.gltf",
      "castle_pack/wall_archer_slit.gltf",
      "castle_pack/wall_archer_slit_large.gltf",
      "castle_pack/wall_lifter.gltf",
      "castle_pack/wall_lifter2.gltf",
      "castle_pack/gate.gltf",
      "castle_pack/gate_small.gltf",
      "castle_pack/gate_portcullis.gltf",
      "castle_pack/portcullis.gltf",
    ],
  },
  {
    label: "CP · Building Roofs",
    category: "building",
    models: [
      "castle_pack/castle_roof_plaster.gltf",
      "castle_pack/castle_roof_plaster_small.gltf",
      "castle_pack/castle_roof_stone.gltf",
      "castle_pack/castle_roof_stone_small.gltf",
      "castle_pack/white_roof_1.gltf",
      "castle_pack/white_roof_2.gltf",
      "castle_pack/wood_roof_1.gltf",
      "castle_pack/wood_roof_2.gltf",
      "castle_pack/wall_roof_small.gltf",
    ],
  },
  {
    label: "CP · Tudor Walls",
    category: "building",
    models: [
      "castle_pack/tudor_wall_2.gltf",
      "castle_pack/tudor_wall_3.gltf",
      "castle_pack/tudor_wall_4.gltf",
      "castle_pack/tudor_wall_5.gltf",
      "castle_pack/tudor_wall_6.gltf",
      "castle_pack/tudor_wall_7.gltf",
      "castle_pack/tudor_wall_8.gltf",
      "castle_pack/tudor_wall_9.gltf",
      "castle_pack/tudor_door_wall_1.gltf",
      "castle_pack/tudor_door_wall_2.gltf",
      "castle_pack/tudor_door_wall_3.gltf",
      "castle_pack/tudor_door_wall_4.gltf",
    ],
  },
  {
    label: "CP · Wood Walls",
    category: "building",
    models: [
      "castle_pack/wood_wall_1.gltf",
      "castle_pack/wood_wall_2.gltf",
      "castle_pack/wood_wall_3.gltf",
      "castle_pack/wood_wall_door_1.gltf",
      "castle_pack/wood_wall_door_2.gltf",
      "castle_pack/short_wood_wall_1.gltf",
      "castle_pack/short_wood_wall_2.gltf",
      "castle_pack/short_wood_wall_3.gltf",
    ],
  },
  {
    label: "CP · Doors & Windows",
    category: "building",
    models: [
      "castle_pack/door.gltf",
      "castle_pack/door_framed.gltf",
      "castle_pack/door_framed_2.gltf",
      "castle_pack/rounded_door.gltf",
      "castle_pack/rounded_door_framed.gltf",
      "castle_pack/wood_window.gltf",
      "castle_pack/stone_windpw.gltf",
      "castle_pack/wooden_trap_door.gltf",
    ],
  },
  {
    label: "CP · Stairs & Walkways",
    category: "building",
    models: [
      "castle_pack/stairs.gltf",
      "castle_pack/stairs_block.gltf",
      "castle_pack/stone_steps.gltf",
      "castle_pack/stone_support.gltf",
      "castle_pack/stone_bridge.gltf",
      "castle_pack/walkway.gltf",
      "castle_pack/wood_corner_stairs.gltf",
      "castle_pack/wood_column.gltf",
      "castle_pack/wood_support.gltf",
      "castle_pack/building_balcony.gltf",
    ],
  },
  {
    label: "CP · Chimneys",
    category: "building",
    models: [
      "castle_pack/chimney_extension.gltf",
      "castle_pack/chimney_top.gltf",
    ],
  },
  {
    label: "CP · Dock & Props",
    category: "building",
    models: [
      "castle_pack/dock_platform.gltf",
      "castle_pack/dock_stairs.gltf",
      "castle_pack/barrel.gltf",
      "castle_pack/crate.gltf",
      "castle_pack/hay_1.gltf",
      "castle_pack/hay_2.gltf",
      "castle_pack/hay_3.gltf",
    ],
  },
  {
    label: "CP · Rocks",
    category: "building",
    models: [
      "castle_pack/rock_1.gltf",
      "castle_pack/rock_2.gltf",
      "castle_pack/rock_3.gltf",
      "castle_pack/rock_4.gltf",
      "castle_pack/rock_5.gltf",
      "castle_pack/rock_6.gltf",
      "castle_pack/rock_7.gltf",
      "castle_pack/rock_8.gltf",
      "castle_pack/rock_9.gltf",
      "castle_pack/rock_10.gltf",
    ],
  },
  {
    label: "CP · Prebuilds",
    category: "building",
    models: [
      "castle_pack/prebuild_cottage.gltf",
      "castle_pack/prebuild_inn.gltf",
      "castle_pack/prebuild_manor.gltf",
      "castle_pack/prebuild_blacksmith.gltf",
      "castle_pack/prebuild_stables.gltf",
      "castle_pack/prebuild_garrison.gltf",
      "castle_pack/prebuild_watchpost.gltf",
      "castle_pack/prebuild_pavilion.gltf",
      "castle_pack/prebuild_small_plaster_home.gltf",
      "castle_pack/prebuild_large_plaster_home.gltf",
      "castle_pack/prebuild_large_wooden_home.gltf",
      "castle_pack/prebuild_wood_shack.gltf",
      "castle_pack/prebuild_wood_shack_2.gltf",
      "castle_pack/prebuild_fishing_house.gltf",
      "castle_pack/prebuild_docks.gltf",
      "castle_pack/prebuild_warf.gltf",
      "castle_pack/prebuild_castle_entrance.gltf",
      "castle_pack/prebuild_round_tower.gltf",
      "castle_pack/prebuild_round_tower_tall.gltf",
      "castle_pack/prebuild_round_tower_interior.gltf",
      "castle_pack/prebuild_square_tower.gltf",
      "castle_pack/prebuild_square_tower_interior.gltf",
    ],
  },

  // ── Castle Ruins (palette atlas) ─────────────────────────────────────────
  // Converted from OBJ + palette color.png → self-contained GLB.
  {
    label: "Castle Ruins",
    category: "building",
    models: [
      "castle_ruins/CastleRuins.glb",
    ],
  },

  // ── KayKit Medieval Hexagon Pack (FREE 1.0) ─────────────────────────────
  // buildings → buildings/kaykit_hexagon/
  // nature    → foliage/kaykit_hexagon/
  // props/tiles → props/kaykit_hexagon/
  {
    label: "KH · Buildings (Green)",
    category: "building",
    models: [
      "kaykit_hexagon/green/building_archeryrange_green.gltf",
      "kaykit_hexagon/green/building_barracks_green.gltf",
      "kaykit_hexagon/green/building_blacksmith_green.gltf",
      "kaykit_hexagon/green/building_castle_green.gltf",
      "kaykit_hexagon/green/building_church_green.gltf",
      "kaykit_hexagon/green/building_home_A_green.gltf",
      "kaykit_hexagon/green/building_home_B_green.gltf",
      "kaykit_hexagon/green/building_lumbermill_green.gltf",
      "kaykit_hexagon/green/building_market_green.gltf",
      "kaykit_hexagon/green/building_mine_green.gltf",
      "kaykit_hexagon/green/building_tavern_green.gltf",
      "kaykit_hexagon/green/building_tower_A_green.gltf",
      "kaykit_hexagon/green/building_tower_B_green.gltf",
      "kaykit_hexagon/green/building_tower_base_green.gltf",
      "kaykit_hexagon/green/building_tower_catapult_green.gltf",
      "kaykit_hexagon/green/building_watermill_green.gltf",
      "kaykit_hexagon/green/building_well_green.gltf",
      "kaykit_hexagon/green/building_windmill_green.gltf",
    ],
  },
  {
    label: "KH · Buildings (Blue)",
    category: "building",
    models: [
      "kaykit_hexagon/blue/building_archeryrange_blue.gltf",
      "kaykit_hexagon/blue/building_barracks_blue.gltf",
      "kaykit_hexagon/blue/building_blacksmith_blue.gltf",
      "kaykit_hexagon/blue/building_castle_blue.gltf",
      "kaykit_hexagon/blue/building_church_blue.gltf",
      "kaykit_hexagon/blue/building_home_A_blue.gltf",
      "kaykit_hexagon/blue/building_home_B_blue.gltf",
      "kaykit_hexagon/blue/building_lumbermill_blue.gltf",
      "kaykit_hexagon/blue/building_market_blue.gltf",
      "kaykit_hexagon/blue/building_mine_blue.gltf",
      "kaykit_hexagon/blue/building_tavern_blue.gltf",
      "kaykit_hexagon/blue/building_tower_A_blue.gltf",
      "kaykit_hexagon/blue/building_tower_B_blue.gltf",
      "kaykit_hexagon/blue/building_tower_base_blue.gltf",
      "kaykit_hexagon/blue/building_tower_catapult_blue.gltf",
      "kaykit_hexagon/blue/building_watermill_blue.gltf",
      "kaykit_hexagon/blue/building_well_blue.gltf",
      "kaykit_hexagon/blue/building_windmill_blue.gltf",
    ],
  },
  {
    label: "KH · Buildings (Red)",
    category: "building",
    models: [
      "kaykit_hexagon/red/building_archeryrange_red.gltf",
      "kaykit_hexagon/red/building_barracks_red.gltf",
      "kaykit_hexagon/red/building_blacksmith_red.gltf",
      "kaykit_hexagon/red/building_castle_red.gltf", "kaykit_hexagon/red/building_church_red.gltf",
      "kaykit_hexagon/red/building_home_A_red.gltf", "kaykit_hexagon/red/building_home_B_red.gltf",
      "kaykit_hexagon/red/building_lumbermill_red.gltf",
      "kaykit_hexagon/red/building_market_red.gltf", "kaykit_hexagon/red/building_mine_red.gltf",
      "kaykit_hexagon/red/building_tavern_red.gltf",
      "kaykit_hexagon/red/building_tower_A_red.gltf",
      "kaykit_hexagon/red/building_tower_B_red.gltf",
      "kaykit_hexagon/red/building_tower_base_red.gltf",
      "kaykit_hexagon/red/building_tower_catapult_red.gltf",
      "kaykit_hexagon/red/building_watermill_red.gltf",
      "kaykit_hexagon/red/building_well_red.gltf", "kaykit_hexagon/red/building_windmill_red.gltf",
    ],
  },
  {
    label: "KH · Buildings (Yellow)",
    category: "building",
    models: [
      "kaykit_hexagon/yellow/building_archeryrange_yellow.gltf",
      "kaykit_hexagon/yellow/building_barracks_yellow.gltf",
      "kaykit_hexagon/yellow/building_blacksmith_yellow.gltf",
      "kaykit_hexagon/yellow/building_castle_yellow.gltf",
      "kaykit_hexagon/yellow/building_church_yellow.gltf",
      "kaykit_hexagon/yellow/building_home_A_yellow.gltf",
      "kaykit_hexagon/yellow/building_home_B_yellow.gltf",
      "kaykit_hexagon/yellow/building_lumbermill_yellow.gltf",
      "kaykit_hexagon/yellow/building_market_yellow.gltf",
      "kaykit_hexagon/yellow/building_mine_yellow.gltf",
      "kaykit_hexagon/yellow/building_tavern_yellow.gltf",
      "kaykit_hexagon/yellow/building_tower_A_yellow.gltf",
      "kaykit_hexagon/yellow/building_tower_B_yellow.gltf",
      "kaykit_hexagon/yellow/building_tower_base_yellow.gltf",
      "kaykit_hexagon/yellow/building_tower_catapult_yellow.gltf",
      "kaykit_hexagon/yellow/building_watermill_yellow.gltf",
      "kaykit_hexagon/yellow/building_well_yellow.gltf",
      "kaykit_hexagon/yellow/building_windmill_yellow.gltf",
    ],
  },
  {
    label: "KH · Buildings (Neutral)",
    category: "building",
    models: [
      "kaykit_hexagon/neutral/building_bridge_A.gltf",
      "kaykit_hexagon/neutral/building_bridge_B.gltf",
      "kaykit_hexagon/neutral/building_destroyed.gltf",
      "kaykit_hexagon/neutral/building_dirt.gltf", "kaykit_hexagon/neutral/building_grain.gltf",
      "kaykit_hexagon/neutral/building_scaffolding.gltf",
      "kaykit_hexagon/neutral/building_stage_A.gltf",
      "kaykit_hexagon/neutral/building_stage_B.gltf",
      "kaykit_hexagon/neutral/building_stage_C.gltf",
      "kaykit_hexagon/neutral/fence_stone_straight.gltf",
      "kaykit_hexagon/neutral/fence_stone_straight_gate.gltf",
      "kaykit_hexagon/neutral/fence_wood_straight.gltf",
      "kaykit_hexagon/neutral/fence_wood_straight_gate.gltf",
      "kaykit_hexagon/neutral/projectile_catapult.gltf",
      "kaykit_hexagon/neutral/wall_corner_A_gate.gltf",
      "kaykit_hexagon/neutral/wall_corner_A_inside.gltf",
      "kaykit_hexagon/neutral/wall_corner_A_outside.gltf",
      "kaykit_hexagon/neutral/wall_corner_B_inside.gltf",
      "kaykit_hexagon/neutral/wall_corner_B_outside.gltf",
      "kaykit_hexagon/neutral/wall_straight.gltf",
      "kaykit_hexagon/neutral/wall_straight_gate.gltf",
    ],
  },
  {
    label: "KH · Trees",
    category: "foliage",
    models: [
      "kaykit_hexagon/tree_single_A.gltf", "kaykit_hexagon/tree_single_A_cut.gltf",
      "kaykit_hexagon/tree_single_B.gltf", "kaykit_hexagon/tree_single_B_cut.gltf",
      "kaykit_hexagon/trees_A_cut.gltf", "kaykit_hexagon/trees_A_large.gltf",
      "kaykit_hexagon/trees_A_medium.gltf", "kaykit_hexagon/trees_A_small.gltf",
      "kaykit_hexagon/trees_B_cut.gltf", "kaykit_hexagon/trees_B_large.gltf",
      "kaykit_hexagon/trees_B_medium.gltf", "kaykit_hexagon/trees_B_small.gltf",
    ],
  },
  {
    label: "KH · Hills & Mountains",
    category: "foliage",
    models: [
      "kaykit_hexagon/hill_single_A.gltf", "kaykit_hexagon/hill_single_B.gltf",
      "kaykit_hexagon/hill_single_C.gltf", "kaykit_hexagon/hills_A.gltf",
      "kaykit_hexagon/hills_A_trees.gltf", "kaykit_hexagon/hills_B.gltf",
      "kaykit_hexagon/hills_B_trees.gltf", "kaykit_hexagon/hills_C.gltf",
      "kaykit_hexagon/hills_C_trees.gltf", "kaykit_hexagon/mountain_A.gltf",
      "kaykit_hexagon/mountain_A_grass.gltf", "kaykit_hexagon/mountain_A_grass_trees.gltf",
      "kaykit_hexagon/mountain_B.gltf", "kaykit_hexagon/mountain_B_grass.gltf",
      "kaykit_hexagon/mountain_B_grass_trees.gltf", "kaykit_hexagon/mountain_C.gltf",
      "kaykit_hexagon/mountain_C_grass.gltf", "kaykit_hexagon/mountain_C_grass_trees.gltf",
    ],
  },
  {
    label: "KH · Rocks & Water Plants",
    category: "foliage",
    models: [
      "kaykit_hexagon/cloud_big.gltf", "kaykit_hexagon/cloud_small.gltf",
      "kaykit_hexagon/rock_single_A.gltf", "kaykit_hexagon/rock_single_B.gltf",
      "kaykit_hexagon/rock_single_C.gltf", "kaykit_hexagon/rock_single_D.gltf",
      "kaykit_hexagon/rock_single_E.gltf", "kaykit_hexagon/waterlily_A.gltf",
      "kaykit_hexagon/waterlily_B.gltf", "kaykit_hexagon/waterplant_A.gltf",
      "kaykit_hexagon/waterplant_B.gltf", "kaykit_hexagon/waterplant_C.gltf",
    ],
  },
  {
    label: "KH · Props",
    category: "prop",
    models: [
      "kaykit_hexagon/props/barrel.gltf", "kaykit_hexagon/props/bucket_arrows.gltf",
      "kaykit_hexagon/props/bucket_empty.gltf", "kaykit_hexagon/props/bucket_water.gltf",
      "kaykit_hexagon/props/crate_A_big.gltf", "kaykit_hexagon/props/crate_A_small.gltf",
      "kaykit_hexagon/props/crate_B_big.gltf", "kaykit_hexagon/props/crate_B_small.gltf",
      "kaykit_hexagon/props/crate_long_A.gltf", "kaykit_hexagon/props/crate_long_B.gltf",
      "kaykit_hexagon/props/crate_long_C.gltf", "kaykit_hexagon/props/crate_long_empty.gltf",
      "kaykit_hexagon/props/crate_open.gltf", "kaykit_hexagon/props/flag_blue.gltf",
      "kaykit_hexagon/props/flag_green.gltf", "kaykit_hexagon/props/flag_red.gltf",
      "kaykit_hexagon/props/flag_yellow.gltf", "kaykit_hexagon/props/ladder.gltf",
      "kaykit_hexagon/props/pallet.gltf", "kaykit_hexagon/props/resource_lumber.gltf",
      "kaykit_hexagon/props/resource_stone.gltf", "kaykit_hexagon/props/sack.gltf",
      "kaykit_hexagon/props/target.gltf", "kaykit_hexagon/props/tent.gltf",
      "kaykit_hexagon/props/weaponrack.gltf", "kaykit_hexagon/props/wheelbarrow.gltf",
    ],
  },
  {
    label: "KH · Hex Base",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/base/hex_grass.gltf",
      "kaykit_hexagon/tiles/base/hex_grass_bottom.gltf",
      "kaykit_hexagon/tiles/base/hex_grass_sloped_high.gltf",
      "kaykit_hexagon/tiles/base/hex_grass_sloped_low.gltf",
      "kaykit_hexagon/tiles/base/hex_water.gltf",
    ],
  },
  {
    label: "KH · Hex Coast",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/coast/hex_coast_A.gltf", "kaykit_hexagon/tiles/coast/hex_coast_B.gltf",
      "kaykit_hexagon/tiles/coast/hex_coast_C.gltf", "kaykit_hexagon/tiles/coast/hex_coast_D.gltf",
      "kaykit_hexagon/tiles/coast/hex_coast_E.gltf",
    ],
  },
  {
    label: "KH · Hex Coast (dry)",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/coast/waterless/hex_coast_A_waterless.gltf",
      "kaykit_hexagon/tiles/coast/waterless/hex_coast_B_waterless.gltf",
      "kaykit_hexagon/tiles/coast/waterless/hex_coast_C_waterless.gltf",
      "kaykit_hexagon/tiles/coast/waterless/hex_coast_D_waterless.gltf",
      "kaykit_hexagon/tiles/coast/waterless/hex_coast_E_waterless.gltf",
    ],
  },
  {
    label: "KH · Hex Rivers",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/rivers/hex_river_A.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_A_curvy.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_B.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_C.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_D.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_E.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_F.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_G.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_H.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_I.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_J.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_K.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_L.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_crossing_A.gltf",
      "kaykit_hexagon/tiles/rivers/hex_river_crossing_B.gltf",
    ],
  },
  {
    label: "KH · Hex Rivers (dry)",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_A_curvy_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_A_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_B_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_C_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_D_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_E_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_F_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_G_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_H_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_I_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_J_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_K_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_L_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_crossing_A_waterless.gltf",
      "kaykit_hexagon/tiles/rivers/waterless/hex_river_crossing_B_waterless.gltf",
    ],
  },
  {
    label: "KH · Hex Roads",
    category: "prop",
    models: [
      "kaykit_hexagon/tiles/roads/hex_road_A.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_A_sloped_high.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_A_sloped_low.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_B.gltf", "kaykit_hexagon/tiles/roads/hex_road_C.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_D.gltf", "kaykit_hexagon/tiles/roads/hex_road_E.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_F.gltf", "kaykit_hexagon/tiles/roads/hex_road_G.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_H.gltf", "kaykit_hexagon/tiles/roads/hex_road_I.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_J.gltf", "kaykit_hexagon/tiles/roads/hex_road_K.gltf",
      "kaykit_hexagon/tiles/roads/hex_road_L.gltf", "kaykit_hexagon/tiles/roads/hex_road_M.gltf",
    ],
  },

  // ── Fantastic Village Pack (FBX → glTF + shared textures/) ───────────────

  {
    label: "FV · Balconies",
    category: "building",
    models: [
      "fantastic_village/balcony_v01_01.gltf",
      "fantastic_village/balcony_v02_01.gltf",
    ],
  },
  {
    label: "FV · Barrels",
    category: "prop",
    models: [
      "fantastic_village/barrel_01.gltf",
      "fantastic_village/barrel_02.gltf",
      "fantastic_village/barrel_03.gltf",
      "fantastic_village/barrel_04.gltf",
      "fantastic_village/barrel_05.gltf",
      "fantastic_village/barrel_06.gltf",
      "fantastic_village/barrel_07.gltf",
      "fantastic_village/barrel_08.gltf",
    ],
  },
  {
    label: "FV · Bases",
    category: "building",
    models: [
      "fantastic_village/base_v01_01.gltf",
      "fantastic_village/base_v02_01.gltf",
      "fantastic_village/base_v03_01.gltf",
      "fantastic_village/base_v04_01.gltf",
      "fantastic_village/base_v04_02.gltf",
      "fantastic_village/base_v05_01.gltf",
    ],
  },
  {
    label: "FV · Baskets",
    category: "prop",
    models: [
      "fantastic_village/basket_01.gltf",
      "fantastic_village/basket_02.gltf",
      "fantastic_village/basket_03.gltf",
    ],
  },
  {
    label: "FV · Beams (big)",
    category: "building",
    models: [
      "fantastic_village/beam_big_v01_01.gltf",
      "fantastic_village/beam_big_v01_v2.gltf",
      "fantastic_village/beam_big_v02_01.gltf",
      "fantastic_village/beam_big_v02_02.gltf",
      "fantastic_village/beam_big_v03_01.gltf",
      "fantastic_village/beam_big_v03_02.gltf",
      "fantastic_village/beam_big_v03_03.gltf",
    ],
  },
  {
    label: "FV · Beams (small)",
    category: "building",
    models: [
      "fantastic_village/beam_small_v01_01.gltf",
      "fantastic_village/beam_small_v01_02.gltf",
      "fantastic_village/beam_small_v02_01.gltf",
      "fantastic_village/beam_small_v02_02.gltf",
      "fantastic_village/beam_small_v03_01.gltf",
      "fantastic_village/beam_small_v03_02.gltf",
      "fantastic_village/beam_small_v04_01.gltf",
      "fantastic_village/beam_small_v04_02.gltf",
      "fantastic_village/beam_small_v05_01.gltf",
      "fantastic_village/beam_small_v05_02.gltf",
      "fantastic_village/beam_small_v06_01.gltf",
      "fantastic_village/beam_small_v06_02.gltf",
      "fantastic_village/beam_small_v06_03.gltf",
      "fantastic_village/beam_small_v07_01.gltf",
    ],
  },
  {
    label: "FV · Bodies",
    category: "building",
    models: [
      "fantastic_village/body_v01_01.gltf",
      "fantastic_village/body_v01_02.gltf",
      "fantastic_village/body_v02_01.gltf",
      "fantastic_village/body_v02_02.gltf",
      "fantastic_village/body_v03_01.gltf",
      "fantastic_village/body_v03_02.gltf",
      "fantastic_village/body_v04_01.gltf",
      "fantastic_village/body_v04_02.gltf",
      "fantastic_village/body_v05_01.gltf",
      "fantastic_village/body_v05_02.gltf",
      "fantastic_village/body_v06_01.gltf",
      "fantastic_village/body_v06_02.gltf",
      "fantastic_village/body_v07_01.gltf",
      "fantastic_village/body_v07_02.gltf",
    ],
  },
  {
    label: "FV · Body Adds",
    category: "building",
    models: [
      "fantastic_village/body_add_v01_01.gltf",
      "fantastic_village/body_add_v02_01.gltf",
      "fantastic_village/body_add_v03_01.gltf",
      "fantastic_village/body_add_v04_01.gltf",
    ],
  },
  {
    label: "FV · Bottles",
    category: "prop",
    models: [
      "fantastic_village/bottle_01.gltf",
      "fantastic_village/bottle_02.gltf",
      "fantastic_village/bottle_03.gltf",
      "fantastic_village/bottle_04.gltf",
      "fantastic_village/bottle_05.gltf",
      "fantastic_village/bottle_06.gltf",
      "fantastic_village/bottle_07.gltf",
      "fantastic_village/bottle_08.gltf",
      "fantastic_village/bottle_09.gltf",
    ],
  },
  {
    label: "FV · Bowls",
    category: "prop",
    models: [
      "fantastic_village/bowl_metal.gltf",
      "fantastic_village/bowl_wood_01.gltf",
      "fantastic_village/bowl_wood_02.gltf",
      "fantastic_village/bowl_wood_03.gltf",
      "fantastic_village/bowl_wood_04.gltf",
      "fantastic_village/bowl_wood_05.gltf",
    ],
  },
  {
    label: "FV · Boxes & Crates",
    category: "prop",
    models: [
      "fantastic_village/box_01.gltf",
      "fantastic_village/box_02.gltf",
      "fantastic_village/box_03.gltf",
      "fantastic_village/box_04.gltf",
      "fantastic_village/box_05.gltf",
      "fantastic_village/crate_01.gltf",
      "fantastic_village/crate_02.gltf",
      "fantastic_village/crate_03.gltf",
      "fantastic_village/crate_04.gltf",
      "fantastic_village/crate_05.gltf",
    ],
  },
  {
    label: "FV · Bridges",
    category: "prop",
    models: [
      "fantastic_village/bridge_wood_01.gltf",
      "fantastic_village/bridge_wood_02.gltf",
      "fantastic_village/bridge_wood_03.gltf",
      "fantastic_village/bridge_wood_04.gltf",
    ],
  },
  {
    label: "FV · Buckets",
    category: "prop",
    models: [
      "fantastic_village/bucket_01.gltf",
      "fantastic_village/bucket_02.gltf",
      "fantastic_village/bucket_03.gltf",
      "fantastic_village/bucket_04.gltf",
    ],
  },
  {
    label: "FV · Chimneys",
    category: "building",
    models: [
      "fantastic_village/chimney_v01_01.gltf",
      "fantastic_village/chimney_v01_02.gltf",
      "fantastic_village/chimney_v01_03.gltf",
      "fantastic_village/chimney_v02_01.gltf",
      "fantastic_village/chimney_v02_02.gltf",
      "fantastic_village/chimney_v02_03.gltf",
    ],
  },
  {
    label: "FV · Doors",
    category: "building",
    models: [
      "fantastic_village/door_v01_01.gltf",
      "fantastic_village/door_v02_01.gltf",
      "fantastic_village/door_v03_01.gltf",
      "fantastic_village/door_v04_01.gltf",
    ],
  },
  {
    label: "FV · Environment",
    category: "foliage",
    models: [
      "fantastic_village/plant_grass_village.gltf",
      "fantastic_village/plant_leaf_village.gltf",
      "fantastic_village/tree_village.gltf",
    ],
  },
  {
    label: "FV · Fences",
    category: "prop",
    models: [
      "fantastic_village/fence_door_gate.gltf",
      "fantastic_village/fence_v01_01.gltf",
      "fantastic_village/fence_v01_02.gltf",
      "fantastic_village/fence_v01_03.gltf",
      "fantastic_village/fence_v01_04.gltf",
      "fantastic_village/fence_v01_05.gltf",
      "fantastic_village/fence_v02_01.gltf",
      "fantastic_village/fence_v02_02.gltf",
      "fantastic_village/fence_v02_03.gltf",
      "fantastic_village/fence_v02_04.gltf",
      "fantastic_village/fence_v03_01.gltf",
      "fantastic_village/fence_v03_02.gltf",
      "fantastic_village/fence_v03_03.gltf",
      "fantastic_village/fence_v03_04.gltf",
      "fantastic_village/fence_v04_01.gltf",
      "fantastic_village/fence_v04_02.gltf",
      "fantastic_village/fence_v04_03.gltf",
    ],
  },
  {
    label: "FV · Flags",
    category: "prop",
    models: [
      "fantastic_village/flag_01.gltf",
      "fantastic_village/flag_02.gltf",
      "fantastic_village/flag_03.gltf",
      "fantastic_village/flag_04.gltf",
      "fantastic_village/flag_05.gltf",
      "fantastic_village/flag_06.gltf",
    ],
  },
  {
    label: "FV · Food",
    category: "prop",
    models: [
      "fantastic_village/food_apple.gltf",
      "fantastic_village/food_banana_01.gltf",
      "fantastic_village/food_banana_02.gltf",
      "fantastic_village/food_bellpepper.gltf",
      "fantastic_village/food_bread_01.gltf",
      "fantastic_village/food_bread_02.gltf",
      "fantastic_village/food_bread_03.gltf",
      "fantastic_village/food_bread_04.gltf",
      "fantastic_village/food_bread_05.gltf",
      "fantastic_village/food_bread_06.gltf",
      "fantastic_village/food_bread_07.gltf",
      "fantastic_village/food_bread_08.gltf",
      "fantastic_village/food_bread_09.gltf",
      "fantastic_village/food_bread_10.gltf",
      "fantastic_village/food_bread_11.gltf",
      "fantastic_village/food_broccoli.gltf",
      "fantastic_village/food_carrot_01.gltf",
      "fantastic_village/food_carrot_02.gltf",
      "fantastic_village/food_cauliflower.gltf",
      "fantastic_village/food_cheese_01.gltf",
      "fantastic_village/food_cheese_02.gltf",
      "fantastic_village/food_cheese_03.gltf",
      "fantastic_village/food_cheese_04.gltf",
      "fantastic_village/food_cheese_05.gltf",
      "fantastic_village/food_cheese_06.gltf",
      "fantastic_village/food_chili_01.gltf",
      "fantastic_village/food_chili_02.gltf",
      "fantastic_village/food_chili_03.gltf",
      "fantastic_village/food_chili_04.gltf",
      "fantastic_village/food_coconut_01.gltf",
      "fantastic_village/food_coconut_02.gltf",
      "fantastic_village/food_corn.gltf",
      "fantastic_village/food_cucumber_01.gltf",
      "fantastic_village/food_cucumber_02.gltf",
      "fantastic_village/food_cucumber_03.gltf",
      "fantastic_village/food_egg_01.gltf",
      "fantastic_village/food_egg_02.gltf",
      "fantastic_village/food_egg_03.gltf",
      "fantastic_village/food_egg_04.gltf",
      "fantastic_village/food_egg_05.gltf",
      "fantastic_village/food_fish_01.gltf",
      "fantastic_village/food_fish_02.gltf",
      "fantastic_village/food_garlic.gltf",
      "fantastic_village/food_grapes_01.gltf",
      "fantastic_village/food_grapes_02.gltf",
      "fantastic_village/food_leek.gltf",
      "fantastic_village/food_lemon_01.gltf",
      "fantastic_village/food_lemon_02.gltf",
      "fantastic_village/food_lemon_03.gltf",
      "fantastic_village/food_mango_01.gltf",
      "fantastic_village/food_mango_02.gltf",
      "fantastic_village/food_meat_01.gltf",
      "fantastic_village/food_meat_02.gltf",
      "fantastic_village/food_meat_03.gltf",
      "fantastic_village/food_meat_04.gltf",
      "fantastic_village/food_meat_05.gltf",
      "fantastic_village/food_meat_06.gltf",
      "fantastic_village/food_meat_07.gltf",
      "fantastic_village/food_meat_08.gltf",
      "fantastic_village/food_meat_09.gltf",
      "fantastic_village/food_meat_10.gltf",
      "fantastic_village/food_meat_11.gltf",
      "fantastic_village/food_mushroom_01.gltf",
      "fantastic_village/food_mushroom_02.gltf",
      "fantastic_village/food_onion.gltf",
      "fantastic_village/food_orange_01.gltf",
      "fantastic_village/food_orange_02.gltf",
      "fantastic_village/food_pear.gltf",
      "fantastic_village/food_plum.gltf",
      "fantastic_village/food_potato_01.gltf",
      "fantastic_village/food_potato_02.gltf",
      "fantastic_village/food_potato_03.gltf",
      "fantastic_village/food_pumpkin_01.gltf",
      "fantastic_village/food_pumpkin_02.gltf",
      "fantastic_village/food_pumpkin_03.gltf",
      "fantastic_village/food_pumpkin_04.gltf",
      "fantastic_village/food_salad.gltf",
      "fantastic_village/food_sausage_01.gltf",
      "fantastic_village/food_sausage_02.gltf",
      "fantastic_village/food_sausage_03.gltf",
      "fantastic_village/food_sausage_04.gltf",
      "fantastic_village/food_sausage_05.gltf",
      "fantastic_village/food_sausage_06.gltf",
      "fantastic_village/food_springonion.gltf",
      "fantastic_village/food_tomato.gltf",
      "fantastic_village/food_turnip.gltf",
      "fantastic_village/food_watermelon_01.gltf",
      "fantastic_village/food_watermelon_02.gltf",
      "fantastic_village/food_watermelon_03.gltf",
      "fantastic_village/food_watermelon_04.gltf",
    ],
  },
  {
    label: "FV · Furniture",
    category: "prop",
    models: [
      "fantastic_village/bench_01.gltf",
      "fantastic_village/bench_02.gltf",
      "fantastic_village/table_01.gltf",
      "fantastic_village/table_02.gltf",
      "fantastic_village/table_03.gltf",
      "fantastic_village/table_04.gltf",
    ],
  },
  {
    label: "FV · Hay",
    category: "prop",
    models: [
      "fantastic_village/hay_01.gltf",
      "fantastic_village/hay_02.gltf",
      "fantastic_village/hay_03.gltf",
      "fantastic_village/hay_04.gltf",
      "fantastic_village/hay_05.gltf",
      "fantastic_village/hay_06.gltf",
    ],
  },
  {
    label: "FV · Lighting",
    category: "prop",
    models: [
      "fantastic_village/brazier_01.gltf",
      "fantastic_village/brazier_02.gltf",
      "fantastic_village/brazier_03.gltf",
      "fantastic_village/brazier_04.gltf",
      "fantastic_village/brazier_05.gltf",
      "fantastic_village/lantern_01.gltf",
      "fantastic_village/lantern_02.gltf",
      "fantastic_village/lantern_03.gltf",
      "fantastic_village/lantern_04.gltf",
      "fantastic_village/streetlamp_v01_01.gltf",
      "fantastic_village/streetlamp_v01_02.gltf",
      "fantastic_village/streetlamp_v01_03.gltf",
      "fantastic_village/streetlamp_v01_04.gltf",
      "fantastic_village/streetlamp_v02_01.gltf",
      "fantastic_village/streetlamp_v02_02.gltf",
      "fantastic_village/streetlamp_v02_03.gltf",
      "fantastic_village/streetlamp_v02_04.gltf",
    ],
  },
  {
    label: "FV · Market",
    category: "prop",
    models: [
      "fantastic_village/market_shelf_01.gltf",
      "fantastic_village/market_shelf_02.gltf",
      "fantastic_village/market_shelf_03.gltf",
      "fantastic_village/market_v01_01.gltf",
      "fantastic_village/market_v01_02.gltf",
      "fantastic_village/market_v02_01.gltf",
      "fantastic_village/market_v02_02.gltf",
      "fantastic_village/market_v03_01.gltf",
      "fantastic_village/market_v03_02.gltf",
      "fantastic_village/market_v04_01.gltf",
      "fantastic_village/market_v04_02.gltf",
    ],
  },
  {
    label: "FV · Paper",
    category: "prop",
    models: [
      "fantastic_village/paper_01.gltf",
      "fantastic_village/paper_02.gltf",
      "fantastic_village/paper_03.gltf",
      "fantastic_village/paper_04.gltf",
    ],
  },
  {
    label: "FV · Planks",
    category: "prop",
    models: [
      "fantastic_village/planks_01.gltf",
      "fantastic_village/planks_02.gltf",
      "fantastic_village/planks_03.gltf",
    ],
  },
  {
    label: "FV · Plant Pots",
    category: "prop",
    models: [
      "fantastic_village/plant_pot_v1_01.gltf",
      "fantastic_village/plant_pot_v1_02.gltf",
      "fantastic_village/plant_pot_v1_03.gltf",
      "fantastic_village/plant_pot_v1_04.gltf",
      "fantastic_village/plant_pot_v2_01.gltf",
      "fantastic_village/plant_pot_v2_02.gltf",
      "fantastic_village/plant_pot_v2_03.gltf",
      "fantastic_village/plant_pot_v2_04.gltf",
      "fantastic_village/plant_pot_v3_01.gltf",
      "fantastic_village/plant_pot_v3_02.gltf",
      "fantastic_village/plant_pot_v3_03.gltf",
      "fantastic_village/plant_pot_v3_04.gltf",
      "fantastic_village/plant_pot_v4_01.gltf",
      "fantastic_village/plant_pot_v5_01.gltf",
      "fantastic_village/plant_pot_v6_01.gltf",
    ],
  },
  {
    label: "FV · Props Misc",
    category: "prop",
    models: [
      "fantastic_village/board_01.gltf",
      "fantastic_village/board_02.gltf",
      "fantastic_village/bridge_stone_01.gltf",
      "fantastic_village/campfire.gltf",
      "fantastic_village/campfire_poles.gltf",
      "fantastic_village/cart_01.gltf",
      "fantastic_village/cart_02.gltf",
      "fantastic_village/cart_03.gltf",
      "fantastic_village/cart_wheel_big.gltf",
      "fantastic_village/cart_wheel_small.gltf",
      "fantastic_village/chair_02.gltf",
      "fantastic_village/chair_03.gltf",
      "fantastic_village/clothesline_01.gltf",
      "fantastic_village/clothesline_02.gltf",
      "fantastic_village/clothesline_03.gltf",
      "fantastic_village/coffin.gltf",
      "fantastic_village/cookingpot_big.gltf",
      "fantastic_village/cookingpot_small.gltf",
      "fantastic_village/cup.gltf",
      "fantastic_village/firepit.gltf",
      "fantastic_village/firepit_woodpile.gltf",
      "fantastic_village/gallows.gltf",
      "fantastic_village/guillotine.gltf",
      "fantastic_village/hangingboard.gltf",
      "fantastic_village/horsestation.gltf",
      "fantastic_village/knife_01.gltf",
      "fantastic_village/knife_02.gltf",
      "fantastic_village/ladder.gltf",
      "fantastic_village/mailbox.gltf",
      "fantastic_village/outhouse.gltf",
      "fantastic_village/pan.gltf",
      "fantastic_village/pan_lid.gltf",
      "fantastic_village/pitchfork.gltf",
      "fantastic_village/plate_metal_01.gltf",
      "fantastic_village/plate_metal_02.gltf",
      "fantastic_village/plate_wood.gltf",
      "fantastic_village/poster_01.gltf",
      "fantastic_village/poster_02.gltf",
      "fantastic_village/rowboat.gltf",
      "fantastic_village/scroll.gltf",
      "fantastic_village/spoon_01.gltf",
      "fantastic_village/spoon_02.gltf",
      "fantastic_village/stepladder.gltf",
      "fantastic_village/stool_01.gltf",
      "fantastic_village/stool_02.gltf",
      "fantastic_village/treasurechest.gltf",
      "fantastic_village/trough_01.gltf",
      "fantastic_village/trough_02.gltf",
      "fantastic_village/walkway_wood.gltf",
      "fantastic_village/wall_wood.gltf",
      "fantastic_village/weathervane.gltf",
      "fantastic_village/well.gltf",
    ],
  },
  {
    label: "FV · Railings",
    category: "prop",
    models: [
      "fantastic_village/railing_v01_01.gltf",
      "fantastic_village/railing_v01_02.gltf",
      "fantastic_village/railing_v02_01.gltf",
      "fantastic_village/railing_v02_02.gltf",
      "fantastic_village/railing_v03_01.gltf",
      "fantastic_village/railing_v03_02.gltf",
    ],
  },
  {
    label: "FV · Sacks",
    category: "prop",
    models: [
      "fantastic_village/sack_01.gltf",
      "fantastic_village/sack_02.gltf",
      "fantastic_village/sack_03.gltf",
      "fantastic_village/sack_04.gltf",
      "fantastic_village/sack_05.gltf",
      "fantastic_village/sack_06.gltf",
      "fantastic_village/sack_07.gltf",
      "fantastic_village/sack_08.gltf",
      "fantastic_village/sack_09.gltf",
      "fantastic_village/sack_10.gltf",
      "fantastic_village/sack_11.gltf",
    ],
  },
  {
    label: "FV · Signs",
    category: "prop",
    models: [
      "fantastic_village/sign_01.gltf",
      "fantastic_village/sign_02.gltf",
      "fantastic_village/sign_03.gltf",
      "fantastic_village/sign_04.gltf",
      "fantastic_village/sign_05.gltf",
      "fantastic_village/sign_06.gltf",
      "fantastic_village/signpost_01.gltf",
      "fantastic_village/signpost_02.gltf",
      "fantastic_village/signpost_03.gltf",
      "fantastic_village/signpost_04.gltf",
    ],
  },
  {
    label: "FV · Spikes",
    category: "prop",
    models: [
      "fantastic_village/spikes_v01_01.gltf",
      "fantastic_village/spikes_v01_02.gltf",
      "fantastic_village/spikes_v01_03.gltf",
      "fantastic_village/spikes_v02_01.gltf",
      "fantastic_village/spikes_v02_02.gltf",
      "fantastic_village/spikes_v02_03.gltf",
    ],
  },
  {
    label: "FV · Stairs",
    category: "building",
    models: [
      "fantastic_village/stairs_v01_01.gltf",
      "fantastic_village/stairs_v02_01.gltf",
      "fantastic_village/stairs_v02_02.gltf",
      "fantastic_village/stairs_v03_v1.gltf",
      "fantastic_village/stairs_v03_v2.gltf",
      "fantastic_village/stairs_v04_v1.gltf",
      "fantastic_village/stairs_v04_v2.gltf",
    ],
  },
  {
    label: "FV · Stone Walls",
    category: "prop",
    models: [
      "fantastic_village/wall_stone_small_01.gltf",
      "fantastic_village/wall_stone_small_02.gltf",
      "fantastic_village/wall_stone_small_03.gltf",
      "fantastic_village/wall_stone_small_04.gltf",
    ],
  },
  {
    label: "FV · Stones",
    category: "prop",
    models: [
      "fantastic_village/stone_01.gltf",
      "fantastic_village/stone_02.gltf",
      "fantastic_village/stone_03.gltf",
      "fantastic_village/stone_04.gltf",
    ],
  },
  {
    label: "FV · Tree Trunks",
    category: "prop",
    models: [
      "fantastic_village/treetrunk_01.gltf",
      "fantastic_village/treetrunk_02.gltf",
      "fantastic_village/treetrunk_03.gltf",
      "fantastic_village/treetrunk_04.gltf",
    ],
  },
  {
    label: "FV · Watchtowers",
    category: "prop",
    models: [
      "fantastic_village/watchtower_wood_01.gltf",
      "fantastic_village/watchtower_wood_02.gltf",
      "fantastic_village/watchtower_wood_02_small.gltf",
    ],
  },
  {
    label: "FV · Waterwheel",
    category: "building",
    models: [
      "fantastic_village/waterwheel_construct.gltf",
    ],
  },
  {
    label: "FV · Windmill",
    category: "building",
    models: [
      "fantastic_village/windmill_sail.gltf",
    ],
  },
  {
    label: "FV · Windows",
    category: "building",
    models: [
      "fantastic_village/window_v01_01.gltf",
      "fantastic_village/window_v02_01.gltf",
      "fantastic_village/window_v03_01.gltf",
      "fantastic_village/window_v04_01.gltf",
      "fantastic_village/window_v05_01.gltf",
      "fantastic_village/window_v06_01.gltf",
      "fantastic_village/window_v06_02.gltf",
      "fantastic_village/window_v07_01.gltf",
      "fantastic_village/window_v07_02.gltf",
      "fantastic_village/window_v08_01.gltf",
      "fantastic_village/window_v08_02.gltf",
      "fantastic_village/window_v08_03.gltf",
      "fantastic_village/window_v08_04.gltf",
      "fantastic_village/window_v09_01.gltf",
      "fantastic_village/window_v09_02.gltf",
      "fantastic_village/window_v09_03.gltf",
      "fantastic_village/window_v09_04.gltf",
    ],
  },
  {
    label: "FV · Wood Foundations",
    category: "prop",
    models: [
      "fantastic_village/foundation_wood_01.gltf",
      "fantastic_village/foundation_wood_02.gltf",
      "fantastic_village/foundation_wood_03.gltf",
      "fantastic_village/foundation_wood_04.gltf",
      "fantastic_village/foundation_wood_05.gltf",
    ],
  },
  {
    label: "FV · Wood Stairs",
    category: "prop",
    models: [
      "fantastic_village/stairs_wood_01.gltf",
      "fantastic_village/stairs_wood_02.gltf",
      "fantastic_village/stairs_wood_03.gltf",
    ],
  },
  {
    label: "FV · Wood Walls",
    category: "prop",
    models: [
      "fantastic_village/wall_wood_corner_01.gltf",
      "fantastic_village/wall_wood_corner_02.gltf",
      "fantastic_village/wall_wood_gate_frame_01.gltf",
      "fantastic_village/wall_wood_gate_frame_02.gltf",
      "fantastic_village/wall_wood_post_01.gltf",
      "fantastic_village/wall_wood_post_02.gltf",
      "fantastic_village/wall_wood_post_03.gltf",
      "fantastic_village/wall_wood_post_04.gltf",
      "fantastic_village/wall_wood_stairs_01.gltf",
      "fantastic_village/wall_wood_stairs_02.gltf",
    ],
  },

  // ── Fab Free Low Poly Pack ───────────────────────────────────────────────
  {
    label: "FL · Trees",
    category: "foliage",
    models: [
      "free_lowpoly/tree_01.gltf",
      "free_lowpoly/tree_02.gltf",
      "free_lowpoly/tree_06.gltf",
      "free_lowpoly/tree_07.gltf",
      "free_lowpoly/tree_willow.gltf",
      "free_lowpoly/fir_02.gltf",
      "free_lowpoly/fallentree_02.gltf",
      "free_lowpoly/fallentree_04.gltf",
      "free_lowpoly/stump_01.gltf",
      "free_lowpoly/root_01.gltf",
    ],
  },
  {
    label: "FL · Bushes & Flowers",
    category: "foliage",
    models: [
      "free_lowpoly/bush_01.gltf",
      "free_lowpoly/bush_05.gltf",
      "free_lowpoly/foliagebush_01.gltf",
      "free_lowpoly/foliage_03.gltf",
      "free_lowpoly/foliage_04.gltf",
      "free_lowpoly/flower_01.gltf",
      "free_lowpoly/flower_02.gltf",
      "free_lowpoly/grass_01.gltf",
      "free_lowpoly/grass_02.gltf",
      "free_lowpoly/grass_03.gltf",
      "free_lowpoly/grass_04.gltf",
      "free_lowpoly/mushroom_01.gltf",
      "free_lowpoly/mushroom_03.gltf",
      "free_lowpoly/mushroom_05.gltf",
      "free_lowpoly/thorn_03_b.gltf",
      "free_lowpoly/thorn_04_b.gltf",
      "free_lowpoly/thorn_06.gltf",
      "free_lowpoly/thorn_09.gltf",
      "free_lowpoly/cobweb_02.gltf",
      "free_lowpoly/cobweb_03.gltf",
    ],
  },
  {
    label: "FL · Rocks",
    category: "foliage",
    models: [
      "free_lowpoly/rock_02.gltf",
      "free_lowpoly/rock_07.gltf",
      "free_lowpoly/rock_08.gltf",
      "free_lowpoly/rock_10.gltf",
      "free_lowpoly/rock_11.gltf",
      "free_lowpoly/rock_13.gltf",
      "free_lowpoly/rock_15.gltf",
      "free_lowpoly/rock_18.gltf",
      "free_lowpoly/pebble_02.gltf",
    ],
  },
  {
    label: "FL · Structures",
    category: "building",
    models: [
      "free_lowpoly/bridge.gltf",
      "free_lowpoly/platform_01.gltf",
      "free_lowpoly/platform_02.gltf",
      "free_lowpoly/platform_03.gltf",
      "free_lowpoly/stonewall_01.gltf",
      "free_lowpoly/stonewall_01_angle90.gltf",
      "free_lowpoly/stonewall_04.gltf",
      "free_lowpoly/rockwall_02.gltf",
      "free_lowpoly/rockwall_03.gltf",
      "free_lowpoly/mountain_01.gltf",
      "free_lowpoly/terrainedge_02.gltf",
    ],
  },
  {
    label: "FL · Props",
    category: "prop",
    models: [
      "free_lowpoly/campfire.gltf",
      "free_lowpoly/fence_01_a.gltf",
      "free_lowpoly/fence_01_a_nopost.gltf",
      "free_lowpoly/sign_01.gltf",
      "free_lowpoly/signpost_02.gltf",
      "free_lowpoly/rune_01.gltf",
      "free_lowpoly/rune_03.gltf",
      "free_lowpoly/runestone_02.gltf",
      "free_lowpoly/runestone_06.gltf",
      "free_lowpoly/spikes_01.gltf",
    ],
  },
  {
    label: "FL · Creatures",
    category: "prop",
    models: [
      "free_lowpoly/fox_01.gltf",
      "free_lowpoly/wolf_01.gltf",
      "free_lowpoly/spider_01.gltf",
    ],
  },

];

export function regionAssetDisplayName(model: string): string {
  const base = model.split("/").pop() ?? model;
  return base.replace(/\.(gltf|glb)$/i, "");
}

export function regionAssetUrl(category: RegionAssetCategory, model: string): string {
  return `/assets/models/${REGION_ASSET_DIR[category]}/${model}`;
}

export function flattenRegionPalette(
  groups: RegionPropPaletteGroup[] = REGION_PROP_PALETTE,
): RegionPaletteAsset[] {
  const out: RegionPaletteAsset[] = [];
  for (const g of groups) {
    const pack = regionGroupPack(g);
    for (const model of g.models) {
      out.push({ model, category: g.category, group: g.label, pack });
    }
  }
  return out;
}
