import type { RegionAssetCategory } from "@rustcraft/shared";

/** Curated, prefix-grouped organisation of the real nature/building asset
 *  directories for the region editor's asset palette (parallels
 *  dungeonPropPalette.ts's role for the dungeon editor). `category` records
 *  which real directory under assets/models/ each group's files live under
 *  (foliage/, buildings/, props/), since the loader needs the right path
 *  prefix and a RegionAsset can't infer it from the filename alone the way
 *  the dungeon editor's props-only palette could. */
export interface RegionPropPaletteGroup {
  label: string;
  category: RegionAssetCategory;
  models: string[];
}

export const REGION_PROP_PALETTE: RegionPropPaletteGroup[] = [
  {
    label: "Trees",
    category: "foliage",
    models: [
      "oak_1.glb", "oak_2.glb", "oak_3.glb", "oak_4.glb", "oak_5.glb",
      "pine_1.glb", "pine_2.glb", "pine_3.glb", "pine_4.glb", "pine_5.glb",
      "twisted_1.glb", "twisted_2.glb", "twisted_3.glb",
      "dead_1.glb", "dead_2.glb", "dead_3.glb",
    ],
  },
  {
    label: "Ground Cover",
    category: "foliage",
    models: ["bush.glb", "bush_flowers.glb", "fern.glb", "mushroom.glb"],
  },
  {
    label: "Small Rocks",
    category: "foliage",
    models: ["rock_1.glb", "rock_2.glb", "rock_3.glb"],
  },
  {
    label: "Rocks & Boulders",
    category: "prop",
    models: ["rocks.gltf", "rocks_decorated.gltf", "rocks_gold.gltf", "rocks_small.gltf"],
  },
  {
    label: "Lighting Props",
    category: "prop",
    models: ["post_lantern.glb"],
  },
  {
    label: "Buildings",
    category: "building",
    models: [
      "building_home_A.gltf", "building_home_B.gltf", "building_tavern.gltf",
      "building_blacksmith.gltf", "building_market.gltf", "building_church.gltf",
      "building_windmill.gltf", "building_lumbermill.gltf", "building_well.gltf",
      "building_tower_A.gltf", "building_destroyed.gltf", "building_grain.gltf",
      "building_bridge_A.gltf", "building_bridge_B.gltf",
    ],
  },
  {
    label: "Village Clutter",
    category: "building",
    models: [
      "barrel.gltf", "bucket_water.gltf", "crate_A_big.gltf", "crate_A_small.gltf",
      "crate_B_small.gltf", "fence_stone_straight.gltf", "fence_wood_straight.gltf",
      "fence_wood_straight_gate.gltf", "flag_blue.gltf", "flag_red.gltf",
    ],
  },

  // ── Medieval Village MegaKit [Standard] ──────────────────────────────────
  // Files live in public/assets/models/buildings/medieval_village/
  // Model strings include the subfolder prefix; the loader concatenates them
  // as: /assets/models/buildings/{model}
  {
    label: "MV · Walls (Plaster)",
    category: "building",
    models: [
      "medieval_village/Wall_Plaster_Straight.gltf",
      "medieval_village/Wall_Plaster_Straight_Base.gltf",
      "medieval_village/Wall_Plaster_Straight_L.gltf",
      "medieval_village/Wall_Plaster_Straight_R.gltf",
      "medieval_village/Wall_Plaster_Door_Flat.gltf",
      "medieval_village/Wall_Plaster_Door_Round.gltf",
      "medieval_village/Wall_Plaster_Door_RoundInset.gltf",
      "medieval_village/Wall_Plaster_Window_Thin_Round.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Flat.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Flat2.gltf",
      "medieval_village/Wall_Plaster_Window_Wide_Round.gltf",
      "medieval_village/Wall_Plaster_WoodGrid.gltf",
      "medieval_village/Wall_Arch.gltf",
      "medieval_village/Wall_BottomCover.gltf",
    ],
  },
  {
    label: "MV · Walls (Brick)",
    category: "building",
    models: [
      "medieval_village/Wall_UnevenBrick_Straight.gltf",
      "medieval_village/Wall_UnevenBrick_Door_Flat.gltf",
      "medieval_village/Wall_UnevenBrick_Door_Round.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Thin_Round.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Wide_Flat.gltf",
      "medieval_village/Wall_UnevenBrick_Window_Wide_Round.gltf",
    ],
  },
  {
    label: "MV · Corners",
    category: "building",
    models: [
      "medieval_village/Corner_Exterior_Brick.gltf",
      "medieval_village/Corner_ExteriorWide_Brick.gltf",
      "medieval_village/Corner_Exterior_Wood.gltf",
      "medieval_village/Corner_ExteriorWide_Wood.gltf",
      "medieval_village/Corner_Exterior_TopDown.gltf",
      "medieval_village/Corner_Exterior_TopOnly.gltf",
      "medieval_village/Corner_Interior_Big.gltf",
      "medieval_village/Corner_Interior_Small.gltf",
    ],
  },
  {
    label: "MV · Doors & Windows",
    category: "building",
    models: [
      "medieval_village/Door_1_Flat.gltf",
      "medieval_village/Door_1_Round.gltf",
      "medieval_village/Door_2_Flat.gltf",
      "medieval_village/Door_2_Round.gltf",
      "medieval_village/Door_4_Flat.gltf",
      "medieval_village/Door_4_Round.gltf",
      "medieval_village/Door_8_Flat.gltf",
      "medieval_village/Door_8_Round.gltf",
      "medieval_village/DoorFrame_Flat_Brick.gltf",
      "medieval_village/DoorFrame_Flat_WoodDark.gltf",
      "medieval_village/DoorFrame_Round_Brick.gltf",
      "medieval_village/DoorFrame_Round_WoodDark.gltf",
      "medieval_village/Window_Thin_Flat1.gltf",
      "medieval_village/Window_Thin_Round1.gltf",
      "medieval_village/Window_Wide_Flat1.gltf",
      "medieval_village/Window_Wide_Round1.gltf",
      "medieval_village/Window_Roof_Thin.gltf",
      "medieval_village/Window_Roof_Wide.gltf",
      "medieval_village/WindowShutters_Thin_Flat_Closed.gltf",
      "medieval_village/WindowShutters_Thin_Flat_Open.gltf",
      "medieval_village/WindowShutters_Thin_Round_Closed.gltf",
      "medieval_village/WindowShutters_Thin_Round_Open.gltf",
      "medieval_village/WindowShutters_Wide_Flat_Closed.gltf",
      "medieval_village/WindowShutters_Wide_Flat_Open.gltf",
      "medieval_village/WindowShutters_Wide_Round_Closed.gltf",
      "medieval_village/WindowShutters_Wide_Round_Open.gltf",
    ],
  },
  {
    label: "MV · Floors",
    category: "building",
    models: [
      "medieval_village/Floor_Brick.gltf",
      "medieval_village/Floor_RedBrick.gltf",
      "medieval_village/Floor_UnevenBrick.gltf",
      "medieval_village/Floor_WoodDark.gltf",
      "medieval_village/Floor_WoodDark_Half1.gltf",
      "medieval_village/Floor_WoodDark_Half2.gltf",
      "medieval_village/Floor_WoodDark_Half3.gltf",
      "medieval_village/Floor_WoodDark_OverhangCorner.gltf",
      "medieval_village/Floor_WoodDark_OverhangCorner2.gltf",
      "medieval_village/Floor_WoodLight.gltf",
      "medieval_village/Floor_WoodLight_OverhangCorner.gltf",
      "medieval_village/Floor_WoodLight_OverhangCorner2.gltf",
      "medieval_village/HoleCover_90Angle.gltf",
      "medieval_village/HoleCover_90Half.gltf",
      "medieval_village/HoleCover_90Stairs.gltf",
      "medieval_village/HoleCover_Straight.gltf",
      "medieval_village/HoleCover_StraightHalf.gltf",
    ],
  },
  {
    label: "MV · Roofs (Round Tiles)",
    category: "building",
    models: [
      "medieval_village/Roof_RoundTile_2x1.gltf",
      "medieval_village/Roof_RoundTile_2x1_Long.gltf",
      "medieval_village/Roof_2x4_RoundTile.gltf",
      "medieval_village/Roof_RoundTiles_4x4.gltf",
      "medieval_village/Roof_RoundTiles_4x6.gltf",
      "medieval_village/Roof_RoundTiles_4x8.gltf",
      "medieval_village/Roof_RoundTiles_6x4.gltf",
      "medieval_village/Roof_RoundTiles_6x6.gltf",
      "medieval_village/Roof_RoundTiles_6x8.gltf",
      "medieval_village/Roof_RoundTiles_6x10.gltf",
      "medieval_village/Roof_RoundTiles_6x12.gltf",
      "medieval_village/Roof_RoundTiles_6x14.gltf",
      "medieval_village/Roof_RoundTiles_8x8.gltf",
      "medieval_village/Roof_RoundTiles_8x10.gltf",
      "medieval_village/Roof_RoundTiles_8x12.gltf",
      "medieval_village/Roof_RoundTiles_8x14.gltf",
      "medieval_village/Roof_Modular_RoundTiles.gltf",
      "medieval_village/Roof_Tower_RoundTiles.gltf",
      "medieval_village/Roof_Dormer_RoundTile.gltf",
    ],
  },
  {
    label: "MV · Roofs (Wooden)",
    category: "building",
    models: [
      "medieval_village/Roof_Wooden_2x1.gltf",
      "medieval_village/Roof_Wooden_2x1_L.gltf",
      "medieval_village/Roof_Wooden_2x1_R.gltf",
      "medieval_village/Roof_Wooden_2x1_Center.gltf",
      "medieval_village/Roof_Wooden_2x1_Center_Mirror.gltf",
      "medieval_village/Roof_Wooden_2x1_Corner.gltf",
      "medieval_village/Roof_Wooden_2x1_Middle.gltf",
    ],
  },
  {
    label: "MV · Roof Fronts & Overhangs",
    category: "building",
    models: [
      "medieval_village/Roof_Front_Brick2.gltf",
      "medieval_village/Roof_Front_Brick4.gltf",
      "medieval_village/Roof_Front_Brick4_Half_L.gltf",
      "medieval_village/Roof_Front_Brick4_Half_R.gltf",
      "medieval_village/Roof_Front_Brick6.gltf",
      "medieval_village/Roof_Front_Brick6_Half_L.gltf",
      "medieval_village/Roof_Front_Brick6_Half_R.gltf",
      "medieval_village/Roof_Front_Brick8.gltf",
      "medieval_village/Roof_Front_Brick8_Half_L.gltf",
      "medieval_village/Roof_Front_Brick8_Half_R.gltf",
      "medieval_village/Roof_FrontSupports.gltf",
      "medieval_village/Roof_Log.gltf",
      "medieval_village/Roof_Support2.gltf",
      "medieval_village/Overhang_Plaster_Corner.gltf",
      "medieval_village/Overhang_Plaster_Corner_Front.gltf",
      "medieval_village/Overhang_Plaster_Long.gltf",
      "medieval_village/Overhang_Plaster_Short.gltf",
      "medieval_village/Overhang_Roof_Plaster.gltf",
      "medieval_village/Overhang_RoofIncline_Plaster.gltf",
      "medieval_village/Overhang_UnevenBrick_Corner.gltf",
      "medieval_village/Overhang_UnevenBrick_Corner_Front.gltf",
      "medieval_village/Overhang_UnevenBrick_Long.gltf",
      "medieval_village/Overhang_UnevenBrick_Short.gltf",
      "medieval_village/Overhang_Roof_UnevenBricks.gltf",
      "medieval_village/Overhang_RoofIncline_UnevenBricks.gltf",
      "medieval_village/Overhang_Side_Plaster_Long_L.gltf",
      "medieval_village/Overhang_Side_Plaster_Long_R.gltf",
      "medieval_village/Overhang_Side_Plaster_Short_L.gltf",
      "medieval_village/Overhang_Side_Plaster_Short_R.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Long_L.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Long_R.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Short_L.gltf",
      "medieval_village/Overhang_Side_UnevenBrick_Short_R.gltf",
    ],
  },
  {
    label: "MV · Stairs (Exterior)",
    category: "building",
    models: [
      "medieval_village/Stairs_Exterior_Straight.gltf",
      "medieval_village/Stairs_Exterior_Straight_L.gltf",
      "medieval_village/Stairs_Exterior_Straight_R.gltf",
      "medieval_village/Stairs_Exterior_Straight_Center.gltf",
      "medieval_village/Stairs_Exterior_Platform.gltf",
      "medieval_village/Stairs_Exterior_Platform45.gltf",
      "medieval_village/Stairs_Exterior_Platform45Clean.gltf",
      "medieval_village/Stairs_Exterior_PlatformU.gltf",
      "medieval_village/Stairs_Exterior_SidePlatform.gltf",
      "medieval_village/Stairs_Exterior_Sides.gltf",
      "medieval_village/Stairs_Exterior_Sides45.gltf",
      "medieval_village/Stairs_Exterior_SidesU.gltf",
      "medieval_village/Stairs_Exterior_SingleSide.gltf",
      "medieval_village/Stairs_Exterior_SingleSideThick.gltf",
      "medieval_village/Stairs_Exterior_NoFirstStep.gltf",
    ],
  },
  {
    label: "MV · Stairs (Interior)",
    category: "building",
    models: [
      "medieval_village/Stair_Interior_Simple.gltf",
      "medieval_village/Stair_Interior_Solid.gltf",
      "medieval_village/Stair_Interior_SolidExtended.gltf",
      "medieval_village/Stair_Interior_Rails.gltf",
    ],
  },
  {
    label: "MV · Balconies",
    category: "building",
    models: [
      "medieval_village/Balcony_Simple_Straight.gltf",
      "medieval_village/Balcony_Simple_Corner.gltf",
      "medieval_village/Balcony_Cross_Straight.gltf",
      "medieval_village/Balcony_Cross_Corner.gltf",
    ],
  },
  {
    label: "MV · Props & Fences",
    category: "building",
    models: [
      "medieval_village/Prop_Crate.gltf",
      "medieval_village/Prop_Wagon.gltf",
      "medieval_village/Prop_Chimney.gltf",
      "medieval_village/Prop_Chimney2.gltf",
      "medieval_village/Prop_Support.gltf",
      "medieval_village/Prop_WoodenFence_Single.gltf",
      "medieval_village/Prop_WoodenFence_Extension1.gltf",
      "medieval_village/Prop_WoodenFence_Extension2.gltf",
      "medieval_village/Prop_MetalFence_Simple.gltf",
      "medieval_village/Prop_MetalFence_Ornament.gltf",
      "medieval_village/Prop_ExteriorBorder_Corner.gltf",
      "medieval_village/Prop_ExteriorBorder_Straight1.gltf",
      "medieval_village/Prop_ExteriorBorder_Straight2.gltf",
      "medieval_village/Prop_Brick1.gltf",
      "medieval_village/Prop_Brick2.gltf",
      "medieval_village/Prop_Brick3.gltf",
      "medieval_village/Prop_Brick4.gltf",
      "medieval_village/Prop_Vine1.gltf",
      "medieval_village/Prop_Vine2.gltf",
      "medieval_village/Prop_Vine4.gltf",
      "medieval_village/Prop_Vine5.gltf",
      "medieval_village/Prop_Vine6.gltf",
      "medieval_village/Prop_Vine9.gltf",
    ],
  },

  // ── Stylized Nature MegaKit [Standard] ───────────────────────────────────
  // Files live in public/assets/models/foliage/stylized_nature/
  // Model strings include the subfolder prefix; the loader concatenates them
  // as: /assets/models/foliage/{model}
  {
    label: "SN · Common Trees",
    category: "foliage",
    models: [
      "stylized_nature/CommonTree_1.gltf",
      "stylized_nature/CommonTree_2.gltf",
      "stylized_nature/CommonTree_3.gltf",
      "stylized_nature/CommonTree_4.gltf",
      "stylized_nature/CommonTree_5.gltf",
    ],
  },
  {
    label: "SN · Pine Trees",
    category: "foliage",
    models: [
      "stylized_nature/Pine_1.gltf",
      "stylized_nature/Pine_2.gltf",
      "stylized_nature/Pine_3.gltf",
      "stylized_nature/Pine_4.gltf",
      "stylized_nature/Pine_5.gltf",
    ],
  },
  {
    label: "SN · Dead & Twisted Trees",
    category: "foliage",
    models: [
      "stylized_nature/DeadTree_1.gltf",
      "stylized_nature/DeadTree_2.gltf",
      "stylized_nature/DeadTree_3.gltf",
      "stylized_nature/DeadTree_4.gltf",
      "stylized_nature/DeadTree_5.gltf",
      "stylized_nature/TwistedTree_1.gltf",
      "stylized_nature/TwistedTree_2.gltf",
      "stylized_nature/TwistedTree_3.gltf",
      "stylized_nature/TwistedTree_4.gltf",
      "stylized_nature/TwistedTree_5.gltf",
    ],
  },
  {
    label: "SN · Bushes & Ground Cover",
    category: "foliage",
    models: [
      "stylized_nature/Bush_Common.gltf",
      "stylized_nature/Bush_Common_Flowers.gltf",
      "stylized_nature/Fern_1.gltf",
      "stylized_nature/Mushroom_Common.gltf",
      "stylized_nature/Mushroom_Laetiporus.gltf",
      "stylized_nature/Plant_1.gltf",
      "stylized_nature/Plant_1_Big.gltf",
      "stylized_nature/Plant_7.gltf",
      "stylized_nature/Plant_7_Big.gltf",
      "stylized_nature/Clover_1.gltf",
      "stylized_nature/Clover_2.gltf",
    ],
  },
  {
    label: "SN · Flowers & Grass",
    category: "foliage",
    models: [
      "stylized_nature/Flower_3_Single.gltf",
      "stylized_nature/Flower_3_Group.gltf",
      "stylized_nature/Flower_4_Single.gltf",
      "stylized_nature/Flower_4_Group.gltf",
      "stylized_nature/Grass_Common_Short.gltf",
      "stylized_nature/Grass_Common_Tall.gltf",
      "stylized_nature/Grass_Wispy_Short.gltf",
      "stylized_nature/Grass_Wispy_Tall.gltf",
    ],
  },
  {
    label: "SN · Rocks & Pebbles",
    category: "foliage",
    models: [
      "stylized_nature/Rock_Medium_1.gltf",
      "stylized_nature/Rock_Medium_2.gltf",
      "stylized_nature/Rock_Medium_3.gltf",
      "stylized_nature/Pebble_Round_1.gltf",
      "stylized_nature/Pebble_Round_2.gltf",
      "stylized_nature/Pebble_Round_3.gltf",
      "stylized_nature/Pebble_Round_4.gltf",
      "stylized_nature/Pebble_Round_5.gltf",
      "stylized_nature/Pebble_Square_1.gltf",
      "stylized_nature/Pebble_Square_2.gltf",
      "stylized_nature/Pebble_Square_3.gltf",
      "stylized_nature/Pebble_Square_4.gltf",
      "stylized_nature/Pebble_Square_5.gltf",
      "stylized_nature/Pebble_Square_6.gltf",
    ],
  },
  {
    label: "SN · Rock Paths",
    category: "foliage",
    models: [
      "stylized_nature/RockPath_Round_Small_1.gltf",
      "stylized_nature/RockPath_Round_Small_2.gltf",
      "stylized_nature/RockPath_Round_Small_3.gltf",
      "stylized_nature/RockPath_Round_Thin.gltf",
      "stylized_nature/RockPath_Round_Wide.gltf",
      "stylized_nature/RockPath_Square_Small_1.gltf",
      "stylized_nature/RockPath_Square_Small_2.gltf",
      "stylized_nature/RockPath_Square_Small_3.gltf",
      "stylized_nature/RockPath_Square_Thin.gltf",
      "stylized_nature/RockPath_Square_Wide.gltf",
    ],
  },
];
