const ICONS: Record<string, string> = {
  wood: "🪵",
  stone: "🪨",
  hide: "🟤",
  bone: "🦴",
  ancient_dust: "✨",
  berries: "🫐",
  raw_meat: "🥩",
  cooked_meat: "🍖",
  bandage: "🩹",
  axe: "🪓",
  pickaxe: "⛏️",
  spear: "🔱",
  torch: "🔥",
  campfire: "🏕️",
  tome_firebolt: "📕",
  firebolt: "🔥",
  saddle: "🐴",
  raft: "🛶",
  iron_sword: "⚔️",
  apprentice_staff: "🪄",
  twin_daggers: "🔪",
  blessed_mace: "🔨",
  hunting_bow: "🏹",
  grove_staff: "🌳",
  sunforged_blade: "⚔️",
  axe_1handed: "🪓",
  axe_1handed_large: "🪓",
  axe_2handed: "🪓",
  axe_2handed_large: "🪓",
  bow: "🏹",
  crossbow_1handed: "🏹",
  crossbow_2handed: "🏹",
  dagger: "🗡️",
  druid_staff: "🌲",
  wand: "🪄",
  shield_badge: "🛡️",
  shield_round: "🛡️",
  shield_square: "🛡️",
  shield_spikes: "🛡️",
  wrench: "🔧",
  leather_armor: "🥋",
  cloth_robe: "👘",
  minor_healing_potion: "🧪",
  runic_healing_potion: "🍷",
  minor_mana_potion: "🧪",
  runic_mana_potion: "🥣",
  frontline_potion: "🧉",
  potion_focus: "🍹",
  invisibility_potion: "🌫️",
  free_action_potion: "👟",
  flask_titan: "🏺",
  phial_quickness: "🫙",
  copper_ore: "🟠",
  tin_ore: "⚪",
  iron_ore: "🔩",
  mithril_ore: "🔵",
  thorium_ore: "🟢",
  silver_ore: "🥈",
  gold_ore: "🥇",
  mithril_pickaxe: "⛏️",
  thorium_pickaxe: "⛏️",
  wolf_fang: "🦷",
  yeti_claw: "🐾",
  golem_core: "🔮",
  demon_horn: "😈",
  dragon_scale: "🐉",
  fanged_dagger: "🗡️",
  frostclaw_axe: "🪓",
  runic_staff: "🪄",
  demonbone_bow: "🏹",
  dragonscale_ward: "🛡️",
  short_sword: "⚔️",
  broadsword: "⚔️",
  runeblade: "⚔️",
  battle_axe: "🪓",
  war_axe: "🪓",
  short_bow: "🏹",
  longbow: "🏹",
  oak_staff: "🪄",
  arcane_rod: "🪄",
  crystal_wand: "🪄",
  curved_dagger: "🗡️",
  serrated_dagger: "🗡️",
  kite_shield: "🛡️",
  heater_shield: "🛡️",
  halberd: "⚜️",
  reaper_scythe: "⚜️",
  brass_knuckles: "🥊",
  war_gauntlets: "🥊",
  iron_spear: "🔱",
};

const SPELL_ICONS: Record<string, string> = {
  firebolt: "🔥",
  frostbolt: "❄️",
  rend: "🩸",
  charge: "💢",
  backstab: "🗡️",
  poison_strike: "☠️",
  heal: "💚",
  smite: "⚡",
  quick_shot: "🏹",
  piercing_shot: "🎯",
  wrath: "🍃",
  regrowth: "🌿",
  crusader_strike: "🔨",
  divine_favor: "✨",
  whirlwind: "🌀",
  flame_nova: "🔥",
  fan_of_knives: "🔪",
  circle_of_healing: "💛",
  volley: "🌧️",
  thorn_burst: "🌵",
  consecration: "🕯️",
  execute: "💥",
  shield_wall: "🛡️",
  arcane_blast: "🔮",
  blizzard: "🌨️",
  eviscerate: "🗡️",
  garrote: "🩸",
  holy_fire: "🔥",
  renew: "💫",
  aimed_shot: "🎯",
  serpent_sting: "🐍",
  moonfire: "🌙",
  entangling_roots: "🌱",
  hammer_of_wrath: "🔨",
  holy_shield: "🛡️",
  beast_mastery: "🐺",
};

const MOB_ICONS: Record<string, string> = {
  wolf: "🐺",
  dire_wolf: "🐺",
  skeleton_minion: "💀",
  skeleton_warrior: "💀",
  skeleton_rogue: "💀",
};

/** Illustrated CraftPix icon art, overriding the emoji fallback where we have a matching piece. */
const ITEM_IMAGES: Record<string, string> = {
  bone: "/assets/ui/item_bone.png",
  stone: "/assets/ui/item_stone.png",
  tome_firebolt: "/assets/ui/item_tome_firebolt.png",
  twin_daggers: "/assets/ui/weapon_twin_daggers.png",
};

const SPELL_IMAGES: Record<string, string> = {
  firebolt: "/assets/ui/spell_firebolt.png",
  frostbolt: "/assets/ui/spell_frostbolt.png",
  rend: "/assets/ui/spell_rend.png",
  charge: "/assets/ui/spell_battle_fury.png",
  backstab: "/assets/ui/weapon_twin_daggers.png",
  poison_strike: "/assets/ui/spell_poison_strike.png",
  heal: "/assets/ui/spell_heal.png",
  smite: "/assets/ui/spell_smite.png",
};

/** True for values returned by itemIcon/spellIcon/mobIcon that are image paths, not emoji glyphs. */
export function isIconImage(value: string): boolean {
  return value.startsWith("/assets/");
}

export function itemIcon(itemId: string): string {
  return ITEM_IMAGES[itemId] ?? ICONS[itemId] ?? "❔";
}

export function mobIcon(mobType: string): string {
  return MOB_ICONS[mobType] ?? "👹";
}

export function spellIcon(spellId: string): string {
  return SPELL_IMAGES[spellId] ?? SPELL_ICONS[spellId] ?? "✨";
}
